import { MigrationInterface, QueryRunner } from "typeorm";

export class UseTimestamptzForAllTimestamps1755428845014 implements MigrationInterface {
    name = 'UseTimestamptzForAllTimestamps1755428845014'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vessel_telemetry" DROP CONSTRAINT "FK_vessel_telemetry_vessel"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP CONSTRAINT "FK_devices_vessel"`);
        await queryRunner.query(`ALTER TABLE "vessel" DROP CONSTRAINT "FK_vessel_vessel_type"`);
        await queryRunner.query(`ALTER TABLE "vessel" DROP CONSTRAINT "FK_vessel_latest_position"`);
        await queryRunner.query(`ALTER TABLE "tree_stubs" DROP CONSTRAINT "FK_tree_stubs_group"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vessel_telemetry_timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vessel_telemetry_position"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vessel_telemetry_vessel_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_devices_vessel_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tree_stubs_group_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tree_stubs_geometry"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sync_minor_version_major_minor_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sync_minor_version_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_landing_sites_location"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_database_statistics_date"`);
        await queryRunner.query(`CREATE TABLE "tree_stub_groups" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4b77eb3be0ed63a4d957b422610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "vessel" DROP COLUMN "call_sign"`);
        await queryRunner.query(`ALTER TABLE "vessel" DROP CONSTRAINT "UQ_vessel_mmsi"`);
        await queryRunner.query(`ALTER TABLE "vessel" DROP COLUMN "mmsi"`);
        await queryRunner.query(`ALTER TABLE "vessel" DROP CONSTRAINT "UQ_vessel_imo"`);
        await queryRunner.query(`ALTER TABLE "vessel" DROP COLUMN "imo"`);
        await queryRunner.query(`ALTER TABLE "vessel_telemetry" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "vessel_telemetry" ADD "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vessel_type" ALTER COLUMN "color" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vessel_type" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "vessel_type" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vessel_type" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "vessel_type" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "activated_at"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "activated_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "expires_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vessel" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "vessel" ADD "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vessel" DROP COLUMN "last_updated"`);
        await queryRunner.query(`ALTER TABLE "vessel" ADD "last_updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vessel" ALTER COLUMN "vessel_type_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tree_stubs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "tree_stubs" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tree_stubs" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "tree_stubs" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sync_minor_version" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sync_minor_version" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "landing_sites" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "landing_sites" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "landing_sites" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "landing_sites" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "sync_major_version_id_seq" OWNED BY "sync_major_version"."id"`);
        await queryRunner.query(`ALTER TABLE "sync_major_version" ALTER COLUMN "id" SET DEFAULT nextval('"sync_major_version_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "sync_major_version" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sync_major_version" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sync_major_version" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "kml_dataset" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "kml_dataset" ADD "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "kml_dataset" DROP COLUMN "last_updated"`);
        await queryRunner.query(`ALTER TABLE "kml_dataset" ADD "last_updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "last_updated"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "last_updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "routes" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "routes" ADD "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "routes" DROP COLUMN "last_updated"`);
        await queryRunner.query(`ALTER TABLE "routes" ADD "last_updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_1b774d96431645e26257391593" ON "vessel_telemetry" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e5c63c7963b5175b2bc1a327d" ON "vessel_telemetry" USING GiST ("position") `);
        await queryRunner.query(`CREATE INDEX "IDX_76d097a6706d0dd73d055548b2" ON "sync_minor_version" ("major_version", "minor_version", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7c91a66785ebca6e6e6ebb63b8" ON "sync_minor_version" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f9888f2ea79fb5cc9101f625f2" ON "landing_sites" USING GiST ("location") `);
        await queryRunner.query(`ALTER TABLE "vessel_telemetry" ADD CONSTRAINT "FK_4a096b2c4bf962907f3dcdbc7e2" FOREIGN KEY ("vessel_id") REFERENCES "vessel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devices" ADD CONSTRAINT "FK_a84b73ae2a2a38ec08ecb8337f5" FOREIGN KEY ("vessel_id") REFERENCES "vessel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vessel" ADD CONSTRAINT "FK_3a76de617773467a2f38a961a09" FOREIGN KEY ("vessel_type_id") REFERENCES "vessel_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vessel" ADD CONSTRAINT "FK_58b548f8d9caefb33d46b1b7d2b" FOREIGN KEY ("latest_position_id") REFERENCES "vessel_telemetry"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tree_stubs" ADD CONSTRAINT "FK_aa8eeae696f49be4798441cd8b4" FOREIGN KEY ("group_id") REFERENCES "tree_stub_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tree_stubs" DROP CONSTRAINT "FK_aa8eeae696f49be4798441cd8b4"`);
        await queryRunner.query(`ALTER TABLE "vessel" DROP CONSTRAINT "FK_58b548f8d9caefb33d46b1b7d2b"`);
        await queryRunner.query(`ALTER TABLE "vessel" DROP CONSTRAINT "FK_3a76de617773467a2f38a961a09"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP CONSTRAINT "FK_a84b73ae2a2a38ec08ecb8337f5"`);
        await queryRunner.query(`ALTER TABLE "vessel_telemetry" DROP CONSTRAINT "FK_4a096b2c4bf962907f3dcdbc7e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9888f2ea79fb5cc9101f625f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c91a66785ebca6e6e6ebb63b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76d097a6706d0dd73d055548b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e5c63c7963b5175b2bc1a327d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b774d96431645e26257391593"`);
        await queryRunner.query(`ALTER TABLE "routes" DROP COLUMN "last_updated"`);
        await queryRunner.query(`ALTER TABLE "routes" ADD "last_updated" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "routes" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "routes" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "last_updated"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "last_updated" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "kml_dataset" DROP COLUMN "last_updated"`);
        await queryRunner.query(`ALTER TABLE "kml_dataset" ADD "last_updated" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "kml_dataset" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "kml_dataset" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sync_major_version" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sync_major_version" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sync_major_version" ALTER COLUMN "id" SET DEFAULT nextval('sync_version_id_seq')`);
        await queryRunner.query(`ALTER TABLE "sync_major_version" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "sync_major_version_id_seq"`);
        await queryRunner.query(`ALTER TABLE "landing_sites" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "landing_sites" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "landing_sites" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "landing_sites" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sync_minor_version" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sync_minor_version" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tree_stubs" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "tree_stubs" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tree_stubs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "tree_stubs" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vessel" ALTER COLUMN "vessel_type_id" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "vessel" DROP COLUMN "last_updated"`);
        await queryRunner.query(`ALTER TABLE "vessel" ADD "last_updated" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vessel" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "vessel" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "expires_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "activated_at"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "activated_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "vessel_type" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "vessel_type" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vessel_type" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "vessel_type" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vessel_type" ALTER COLUMN "color" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vessel_telemetry" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "vessel_telemetry" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vessel" ADD "imo" integer`);
        await queryRunner.query(`ALTER TABLE "vessel" ADD CONSTRAINT "UQ_vessel_imo" UNIQUE ("imo")`);
        await queryRunner.query(`ALTER TABLE "vessel" ADD "mmsi" integer`);
        await queryRunner.query(`ALTER TABLE "vessel" ADD CONSTRAINT "UQ_vessel_mmsi" UNIQUE ("mmsi")`);
        await queryRunner.query(`ALTER TABLE "vessel" ADD "call_sign" character varying`);
        await queryRunner.query(`DROP TABLE "tree_stub_groups"`);
        await queryRunner.query(`CREATE INDEX "IDX_database_statistics_date" ON "database_statistics" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_landing_sites_location" ON "landing_sites" USING GiST ("location") `);
        await queryRunner.query(`CREATE INDEX "IDX_sync_minor_version_created_at" ON "sync_minor_version" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_sync_minor_version_major_minor_created" ON "sync_minor_version" ("created_at", "major_version", "minor_version") `);
        await queryRunner.query(`CREATE INDEX "IDX_tree_stubs_geometry" ON "tree_stubs" USING GiST ("geometry") `);
        await queryRunner.query(`CREATE INDEX "IDX_tree_stubs_group_id" ON "tree_stubs" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_devices_vessel_id" ON "devices" ("vessel_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_vessel_telemetry_vessel_id" ON "vessel_telemetry" ("vessel_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_vessel_telemetry_position" ON "vessel_telemetry" USING GiST ("position") `);
        await queryRunner.query(`CREATE INDEX "IDX_vessel_telemetry_timestamp" ON "vessel_telemetry" ("timestamp") `);
        await queryRunner.query(`ALTER TABLE "tree_stubs" ADD CONSTRAINT "FK_tree_stubs_group" FOREIGN KEY ("group_id") REFERENCES "tree_stub_group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vessel" ADD CONSTRAINT "FK_vessel_latest_position" FOREIGN KEY ("latest_position_id") REFERENCES "vessel_telemetry"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vessel" ADD CONSTRAINT "FK_vessel_vessel_type" FOREIGN KEY ("vessel_type_id") REFERENCES "vessel_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devices" ADD CONSTRAINT "FK_devices_vessel" FOREIGN KEY ("vessel_id") REFERENCES "vessel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vessel_telemetry" ADD CONSTRAINT "FK_vessel_telemetry_vessel" FOREIGN KEY ("vessel_id") REFERENCES "vessel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
